name: Close pull requests
on:
  pull_request_target:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "This repository contains releases only and does not accept contributions. Please [view the README for more details](https://github.com/ametools/gaffer#readme)."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
